dataset:
  dataset_annotations: "F:\\hagrid\\download\\subsample\\ann_subsample\\ann_subsample" # Path to annotations
  dataset_folder: "F:\\hagrid\\download\\subsample\\subsample" # Path to images
  phases: [train, test] #names of annotation directories
  targets:
    - call
    - dislike
    - fist
    - four
    - like
    - mute
    - ok
    - one
    - palm
    - peace
    - rock
    - stop
    - stop_inverted
    - three
    - two_up
    - two_up_inverted
    - three2
    - peace_inverted
    - no_gesture
