dataset:
  dataset_annotations: "/home/leo/myhome/hagrid/download/ann_subsample" # Path to annotations
  dataset_folder: "/home/leo/myhome/hagrid/download/subsample" # Path to images
  phases: [train] #names of annotation directories
  targets:
    - call
    - dislike
    - fist
    - four
    - like
    - mute
    - ok
    - one
    - palm
    - peace
    - rock
    - stop
    - stop_inverted
    - three
    - two_up
    - two_up_inverted
    - three2
    - peace_inverted
    - no_gesture
